using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

const string DefaultSource = "WcsSystem/Wcs.PlcService/Config/db500-keys.json";
const string DefaultOutput = "WcsSystem/Wcs.PlcService/Plc/Db500Map.g.cs";

var repoRoot = FindRepoRoot(AppContext.BaseDirectory);
var sourcePath = args.Length > 0
    ? args[0]
    : Environment.GetEnvironmentVariable("WCS_DB500_KEYS") ?? DefaultSource;
var outputPath = args.Length > 1 ? args[1] : DefaultOutput;

sourcePath = ResolvePath(repoRoot, sourcePath);
outputPath = ResolvePath(repoRoot, outputPath);

var catalog = ReadCatalog(sourcePath);
var generated = Generate(catalog, sourcePath, repoRoot);

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, generated, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

Console.WriteLine($"Generated {outputPath}");

static string FindRepoRoot(string startPath)
{
    var directory = new DirectoryInfo(startPath);

    while (directory is not null)
    {
        if (Directory.Exists(Path.Combine(directory.FullName, ".git")) ||
            Directory.Exists(Path.Combine(directory.FullName, "WcsSystem")))
        {
            return directory.FullName;
        }

        directory = directory.Parent;
    }

    return Directory.GetCurrentDirectory();
}

static string ResolvePath(string repoRoot, string path)
{
    return Path.GetFullPath(Path.IsPathRooted(path) ? path : Path.Combine(repoRoot, path));
}

static Catalog ReadCatalog(string sourcePath)
{
    using var stream = File.OpenRead(sourcePath);
    using var document = JsonDocument.Parse(stream, new JsonDocumentOptions
    {
        AllowTrailingCommas = true,
        CommentHandling = JsonCommentHandling.Skip
    });

    var fields = new List<Field>();

    foreach (var field in document.RootElement.GetProperty("fields").EnumerateArray())
    {
        fields.Add(new Field(
            field.GetProperty("key").GetString() ?? throw new InvalidOperationException("Field key is required."),
            field.GetProperty("address").GetString() ?? throw new InvalidOperationException("Field address is required."),
            field.TryGetProperty("length", out var length) ? length.GetInt32() : null));
    }

    return new Catalog(fields);
}

static string Generate(Catalog catalog, string sourcePath, string repoRoot)
{
    var sourceLabel = Path.GetRelativePath(repoRoot, sourcePath).Replace('\\', '/');
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated>");
    builder.AppendLine($"// Generated by tools/Db500MapGen from {sourceLabel}.");
    builder.AppendLine("// Do not edit by hand.");
    builder.AppendLine("// </auto-generated>");
    builder.AppendLine();
    builder.AppendLine("namespace Wcs.PlcService.Plc;");
    builder.AppendLine();
    builder.AppendLine("public static partial class Db500Map");
    builder.AppendLine("{");

    foreach (var field in catalog.Fields)
    {
        ValidateIdentifier(field.Key);
        builder.AppendLine($"    public const string {field.Key} = \"{field.Address}\";");

        if (field.Length is { } length)
        {
            var byteStart = TryParseDbByteAddress(field.Address);

            builder.AppendLine($"    public const int {field.Key}Length = {length};");

            if (byteStart is { } parsed)
            {
                builder.AppendLine($"    public const int {field.Key}DbNumber = {parsed.DbNumber};");
                builder.AppendLine($"    public const int {field.Key}ByteStart = {parsed.ByteStart};");
            }
        }
    }

    builder.AppendLine("}");

    return builder.ToString();
}

static void ValidateIdentifier(string value)
{
    if (!Regex.IsMatch(value, "^[A-Za-z_][A-Za-z0-9_]*$"))
        throw new InvalidOperationException($"'{value}' is not a valid C# identifier.");
}

static DbByteAddress? TryParseDbByteAddress(string address)
{
    var match = Regex.Match(address, "^DB(?<db>[0-9]+)\\.DBB(?<start>[0-9]+)$");
    if (!match.Success)
        return null;

    return new DbByteAddress(
        int.Parse(match.Groups["db"].Value),
        int.Parse(match.Groups["start"].Value));
}

file sealed record Catalog(IReadOnlyList<Field> Fields);
file sealed record Field(string Key, string Address, int? Length);
file sealed record DbByteAddress(int DbNumber, int ByteStart);
