// <auto-generated>
// Generated by tools/Db500MapGen from WcsSystem/Wcs.PlcService/Config/db500-keys.json.
// Do not edit by hand.
// </auto-generated>

namespace Wcs.PlcService.Plc;

public static partial class Db500Map
{
    public const string reqImportPallet = "DB500.DBX0.0";
    public const string reqExportPallet = "DB500.DBX0.1";
    public const string reqTransferPallet = "DB500.DBX0.2";
    public const string modeCraneShuttle = "DB500.DBW2";
    public const string xin = "DB500.DBW4";
    public const string zin = "DB500.DBW6";
    public const string bin = "DB500.DBW8";
    public const string xout = "DB500.DBW10";
    public const string zout = "DB500.DBW12";
    public const string bout = "DB500.DBW14";
    public const string craneFree = "DB500.DBX16.0";
    public const string craneBusy = "DB500.DBX16.1";
    public const string craneError = "DB500.DBX16.2";
    public const string craneErrorCode = "DB500.DBW18";
    public const string shuttle1Free = "DB500.DBX20.0";
    public const string shuttle1Busy = "DB500.DBX20.1";
    public const string shuttle1Error = "DB500.DBX20.2";
    public const string shuttle1ErrorCode = "DB500.DBW22";
    public const string shuttle1Battery = "DB500.DBW24";
    public const string shuttle2Free = "DB500.DBX26.0";
    public const string shuttle2Busy = "DB500.DBX26.1";
    public const string shuttle2Error = "DB500.DBX26.2";
    public const string shuttle2ErrorCode = "DB500.DBW28";
    public const string shuttle2Battery = "DB500.DBW30";
    public const string barcode = "DB500.DBB32";
    public const int barcodeLength = 14;
    public const int barcodeDbNumber = 500;
    public const int barcodeByteStart = 32;
    public const string barcodeOk = "DB500.DBX46.0";
    public const string barcodeNg = "DB500.DBX46.1";
    public const string plcDone = "DB500.DBX48.0";
    public const string sysAuto = "DB500.DBX50.0";
    public const string sysRunning = "DB500.DBX50.1";
    public const string sysStop = "DB500.DBX50.2";
    public const string sysError = "DB500.DBX50.3";
    public const string sysErrorCode = "DB500.DBW52";
    public const string craneX = "DB500.DBW54";
    public const string craneZ = "DB500.DBW56";
    public const string shuttle1X = "DB500.DBW58";
    public const string shuttle1Z = "DB500.DBW60";
    public const string shuttle1B = "DB500.DBW62";
    public const string shuttle2X = "DB500.DBW64";
    public const string shuttle2Z = "DB500.DBW66";
    public const string shuttle2B = "DB500.DBW68";
    public const string gate = "DB500.DBW70";
    public const string wcsHeartbeat = "DB500.DBX74.0";
}
